apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: f3rrari-com-tls
spec:
  secretName: f3rrari-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: f3rrari.com
  dnsNames:
    - f3rrari.com
    - www.f3rrari.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - f3rrari.com
          - www.f3rrari.com
